/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as billings from "../billings.js";
import type * as clients from "../clients.js";
import type * as collection from "../collection.js";
import type * as groups from "../groups.js";
import type * as inbound from "../inbound.js";
import type * as outbound from "../outbound.js";
import type * as subgroups from "../subgroups.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  billings: typeof billings;
  clients: typeof clients;
  collection: typeof collection;
  groups: typeof groups;
  inbound: typeof inbound;
  outbound: typeof outbound;
  subgroups: typeof subgroups;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
